name: Rails tests
on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RUBY_VERSION: ${{ secrets.RUBY_VERSION }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_HOST: localhost
      SECRET_KEY_BASE: ${{ secrets.AUTH_SECRET }}
      VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
      VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
      NEXT_PUBLIC_AUTHJS_SESSION_COOKIE: ${{ secrets.NEXT_PUBLIC_AUTHJS_SESSION_COOKIE }}
      RAILS_ENV: test

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundler install

      - name: Setup database.yml
        run: |
          cp config/database.yml.example config/database.yml
          # Optionally, you can replace placeholders in database.yml with env variables
          sed -i "s/USERNAME/${{ env.DATABASE_USER }}/" config/database.yml
          sed -i "s/PASSWORD/${{ env.DATABASE_PASSWORD }}/" config/database.yml
          sed -i "s/HOST/${{ env.DATABASE_HOST }}/" config/database.yml
          sed -i "s/DB_NAME/${{ secrets.POSTGRES_DB }}/" config/database.yml

      - name: Create and Migrate Test Database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run RSpec Tests
        run: bundle exec rspec .

      - name: Run Brakeman Security Scanner
        run: brakeman -o brakeman.txt

      - name: Run RuboCop Linter
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload RuboCop Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload Brakeman Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
