name: Rails tests
on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: my_app_test

    env:
      RUBY_VERSION: ${{ secrets.RUBY_VERSION }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_HOST: 127.0.0.1
      SECRET_KEY_BASE: ${{ secrets.AUTH_SECRET }}
      VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
      VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
      NEXT_PUBLIC_AUTHJS_SESSION_COOKIE: ${{ secrets.NEXT_PUBLIC_AUTHJS_SESSION_COOKIE }}
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ secrets.RUBY_VERSION }}  # Ensure Ruby version is set from secrets

      - name: Install postgres client
        run: sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundler install

      - name: Setup database.yml
        run: |
          cp config/database.yml.example config/database.yml

      - name: Create and migrate test database
        run: |
          bundler exec rails db:create
          bundler exec rails db:migrate

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        run: bundler exec rspec .

      - name: Run brakeman
        run: brakeman -o brakeman.txt

      - name: Run rubocop
        run: bundler exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload rubocop report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload brakeman report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
